name: test-e2e-pr

on:
  issue_comment:
    types: [created]

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-e2e:
    if: startsWith(github.event.comment.body, '/test-e2e') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
      - name: PR checkout
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          gh pr checkout $PR_NUM
          tree
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - name: Install azd
        uses: Azure/setup-azd@ae0f8b5482eeac61e940f447327d84c73beb8b1e # v2.1.0

      - name: Install kubelogin
        uses: azure/use-kubelogin@76597ae0fcbaace21b05e13a2cbf8daee2c6e820 # v1
        with:
          kubelogin-version: "v0.2.8"

      - name: Azure login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Developer CLI login
        run: |
          azd auth login \
            --client-id ${{ secrets.AZURE_CLIENT_ID }} \
            --federated-credential-provider "github" \
            --tenant-id ${{ secrets.AZURE_TENANT_ID }}

      - name: Test
        run: |
          printenv
          azd up --no-prompt
        env:
          AZURE_ENV_NAME: test
          AZURE_LOCATION: swedencentral
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Clean up
        run: |
          azd down --force
        env:
          AZURE_ENV_NAME: test
          AZURE_LOCATION: swedencentral
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

